CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    numero_cel VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL UNIQUE,
    id_public VARCHAR(50) NOT NULL UNIQUE,
    pontos_atuais INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lojas (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codigo_publico VARCHAR(50) NOT NULL UNIQUE,
    nome VARCHAR(50) NOT NULL,
    pontos_base INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pontuacoes (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    visitante_id INT NOT NULL REFERENCES users(id),
    loja_id INT NOT NULL REFERENCES lojas(id),
    pontos INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (visitante_id, loja_id)
);

CREATE TABLE IF NOT EXISTS interacoes_hub_juquita (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    visitante_id INT NOT NULL REFERENCES users(id) UNIQUE,
    composicao VARCHAR(50) NOT NULL,
    faixa_etaria VARCHAR(50) NOT NULL,
    local_origem VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS interacoes_lounge_vip (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    visitante_id INT NOT NULL REFERENCES users(id) UNIQUE,
    perfil_consumo VARCHAR(50) NOT NULL,
    intencao_compra VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS brindes (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    custo_pontos INT NOT NULL,
    estoque INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS resgates (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    visitante_id INT NOT NULL REFERENCES users(id),
    brinde_id INT NOT NULL REFERENCES brindes(id),
    pontos_debitados INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS interacoes_acao_guerrilha (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    visitante_id INT NOT NULL REFERENCES users(id) UNIQUE,
    oque_trouxe VARCHAR(50) NOT NULL,
    regiao VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);